### ISSUE TITLE
Wieso "dodel" und nicht "doedel"?

### ISSUE THREAD

**Issue by rpi-fan** [pinae/HaveIBeenPwnedOffline#5]
Passwort-Versuch. dodel
Ergenis:
Searching for hash 5C47559D01FDD7D1146B0B3AAC7DE133FAFDC968 of password "dodel".
Password found at byte  8764798644: "5C47559D01FDD7D1146B0B3AAC7DE133FAFDC968:67"
Your password "dodel" was in 67 leaks or hacked databases! Please change it immediately.

Passt!

Passwort-Versuch: doedel
Ergebnis:
Searching for hash F93DD78B6F835B24FEB76DD27AAF23F36BE59353 of password "doedel".
Traceback (most recent call last):
  File "binary_search.py", line 62, in <module>
    count += binary_search(h, pwned_passwords_file, pwned_passwords_file_size)
  File "binary_search.py", line 33, in binary_search
    return search_hash(list_file, hex_hash, 0, file_size)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 29, in search_hash
    return search_hash(file, my_hash, file.tell(), end)
  File "binary_search.py", line 24, in search_hash
    pwned_hash, count = candidate_line.split(':')
ValueError: need more than 1 value to unpack

**Comment by pinae** [comment]
Eventuell ist ein Fehler in der Datei. Das Skript scheint hier eine Zeile ohne Doppelpunkt zu finden.
